package com.nagardrishti.config;

import com.nagardrishti.entity.Project;
import com.nagardrishti.entity.Scheme;
import com.nagardrishti.repository.ProjectRepository;
import com.nagardrishti.repository.SchemeRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Slf4j @Component @RequiredArgsConstructor
public class DataSeeder implements CommandLineRunner {

    private final SchemeRepository  schemeRepo;
    private final ProjectRepository projectRepo;

    @Override
    public void run(String... args) {
        seedSchemes();
        seedProjects();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SCHEMES
    // ─────────────────────────────────────────────────────────────────────────
    private void seedSchemes() {
        log.info("Seeding schemes (skipping existing)...");

        if (!schemeRepo.existsById("SCH001"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH001").slug("pmmvy")
                    .name("Pradhan Mantri Matru Vandana Yojana").shortTitle("PMMVY")
                    .description("Maternity benefit program providing cash incentives to pregnant and lactating mothers for the first child to improve health-seeking behaviour.")
                    .level("Central").schemeFor("Individual")
                    .schemeCategory(List.of("Women", "Social Welfare"))
                    .beneficiaryState(List.of())
                    .tags(List.of("maternity", "pregnancy", "women", "cash transfer", "anganwadi"))
                    .priority(1)
                    .benefitAmount("₹5,000 in 3 installments").benefitType("Cash Transfer")
                    .minAge(19).maxAge(50).gender("Female").maxIncome(null)
                    .eligibleCategories(List.of("GEN", "OBC", "SC", "ST", "MINORITY"))
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://pmmvy.wcd.gov.in/").helpline("181")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH002"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH002").slug("pmuy")
                    .name("Pradhan Mantri Ujjwala Yojana").shortTitle("PMUY")
                    .description("Provides free LPG connections to women from BPL households to replace polluting cooking fuels.")
                    .level("Central").schemeFor("Family")
                    .schemeCategory(List.of("Women", "Social Welfare"))
                    .beneficiaryState(List.of())
                    .tags(List.of("lpg", "gas connection", "bpl", "cooking", "women"))
                    .priority(2)
                    .benefitAmount("₹1,600 free LPG connection").benefitType("Subsidy")
                    .minAge(18).maxAge(null).gender("Female").maxIncome(200000.0)
                    .eligibleCategories(List.of("SC", "ST")).requiresBpl(true).requiresDisability(false)
                    .officialWebsite("https://pmuy.gov.in/").helpline("1906")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH003"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH003").slug("ignwps")
                    .name("Indira Gandhi National Widow Pension Scheme").shortTitle("IGNWPS")
                    .description("Monthly pension for widows from BPL families aged 40-79 under the National Social Assistance Programme.")
                    .level("Central").schemeFor("Individual")
                    .schemeCategory(List.of("Women", "Social Welfare"))
                    .beneficiaryState(List.of())
                    .tags(List.of("widow", "pension", "bpl", "monthly", "nsap"))
                    .priority(2)
                    .benefitAmount("₹300/month").benefitType("Pension")
                    .minAge(40).maxAge(79).gender("Female").maxIncome(50000.0)
                    .eligibleCategories(List.of("SC", "ST", "OBC", "GEN")).requiresBpl(true).requiresDisability(false)
                    .officialWebsite("https://nsap.nic.in/").helpline("1800-111-555")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH004"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH004").slug("gruha-lakshmi")
                    .name("Gruha Lakshmi Scheme").shortTitle("GRUHA LAKSHMI")
                    .description("Monthly Rs 2,000 financial assistance to the woman head of every eligible family in Karnataka.")
                    .level("State").schemeFor("Family")
                    .schemeCategory(List.of("Women", "Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("women", "monthly", "karnataka", "family", "income support"))
                    .priority(1)
                    .benefitAmount("₹2,000/month").benefitType("Cash Transfer")
                    .minAge(18).maxAge(null).gender("Female").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://sevasindhu.karnataka.gov.in/").helpline("1902")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH005"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH005").slug("bbbp")
                    .name("Beti Bachao Beti Padhao").shortTitle("BBBP")
                    .description("Scheme for welfare and education of the girl child — linked with Sukanya Samriddhi Yojana for long-term savings.")
                    .level("Central").schemeFor("Individual")
                    .schemeCategory(List.of("Women", "Education"))
                    .beneficiaryState(List.of())
                    .tags(List.of("girl child", "education", "sukanya samriddhi", "savings"))
                    .priority(3)
                    .benefitAmount("8.2% interest on savings").benefitType("Savings Scheme")
                    .minAge(0).maxAge(10).gender("Female").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://wcd.nic.in/bbbp-schemes").helpline("181")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH006"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH006").slug("pm-kisan")
                    .name("PM Kisan Samman Nidhi").shortTitle("PM-KISAN")
                    .description("Direct income support of Rs 6,000/year in three installments to all landholding farmer families.")
                    .level("Central").schemeFor("Individual")
                    .schemeCategory(List.of("Agriculture"))
                    .beneficiaryState(List.of())
                    .tags(List.of("farmer", "agriculture", "income support", "kisan", "land"))
                    .priority(1)
                    .benefitAmount("₹6,000/year").benefitType("Cash Transfer")
                    .minAge(18).maxAge(null).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .occupation("Farmer")
                    .requiresBpl(false).requiresDisability(false)
                   // .ownsLand(true).maxLandAllowed(null)
                    .officialWebsite("https://pmkisan.gov.in/").helpline("155261")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH007"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH007").slug("ignoaps")
                    .name("Indira Gandhi National Old Age Pension Scheme").shortTitle("IGNOAPS")
                    .description("Monthly pension for elderly citizens from BPL families under the National Social Assistance Programme.")
                    .level("Central").schemeFor("Individual")
                    .schemeCategory(List.of("Social Welfare"))
                    .beneficiaryState(List.of())
                    .tags(List.of("elderly", "pension", "old age", "bpl", "senior citizen"))
                    .priority(2)
                    .benefitAmount("₹200-500/month").benefitType("Pension")
                    .minAge(60).maxAge(null).gender("All").maxIncome(50000.0)
                    .eligibleCategories(List.of()).requiresBpl(true).requiresDisability(false)
                    .officialWebsite("https://nsap.nic.in/").helpline("1800-111-555")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH008"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH008").slug("pmay-g")
                    .name("Pradhan Mantri Awas Yojana - Gramin").shortTitle("PMAY-G")
                    .description("Provides pucca houses to rural BPL, homeless or kutcha-house families.")
                    .level("Central").schemeFor("Family")
                    .schemeCategory(List.of("Housing"))
                    .beneficiaryState(List.of())
                    .tags(List.of("housing", "house", "bpl", "rural", "pmay"))
                    .priority(1)
                    .benefitAmount("₹1.20-1.30 lakh").benefitType("Subsidy")
                    .minAge(18).maxAge(null).gender("All").maxIncome(300000.0)
                    .eligibleCategories(List.of("SC", "ST")).requiresBpl(true).requiresDisability(false)
                    .officialWebsite("https://pmayg.nic.in/").helpline("1800-11-6446")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH009"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH009").slug("nsp-pms")
                    .name("National Scholarship Portal - Post Matric").shortTitle("NSP Post Matric")
                    .description("Scholarship for SC/ST/OBC/Minority students in post-matric classes covering tuition and maintenance.")
                    .level("Central").schemeFor("Individual")
                    .schemeCategory(List.of("Education"))
                    .beneficiaryState(List.of())
                    .tags(List.of("scholarship", "student", "post matric", "sc", "st", "obc", "minority", "education"))
                    .priority(1)
                    .benefitAmount("₹25,000/year + maintenance").benefitType("Scholarship")
                    .minAge(14).maxAge(30).gender("All").maxIncome(250000.0)
                    .eligibleCategories(List.of("SC", "ST", "OBC", "MINORITY"))
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://scholarships.gov.in/").helpline("0120-6619540")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH010"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH010").slug("pmjay")
                    .name("Ayushman Bharat - PM Jan Arogya Yojana").shortTitle("PMJAY / AB-PMJAY")
                    .description("Health insurance cover of Rs 5 lakh per family per year for cashless hospitalisation at empanelled hospitals.")
                    .level("Central").schemeFor("Family")
                    .schemeCategory(List.of("Health"))
                    .beneficiaryState(List.of())
                    .tags(List.of("health insurance", "hospital", "medical", "bpl", "ayushman", "cashless"))
                    .priority(1)
                    .benefitAmount("₹5 lakh/year health cover").benefitType("Insurance")
                    .minAge(0).maxAge(null).gender("All").maxIncome(150000.0)
                    .eligibleCategories(List.of("SC", "ST")).requiresBpl(true).requiresDisability(false)
                    .officialWebsite("https://pmjay.gov.in/").helpline("14555")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH011"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH011").slug("shakti")
                    .name("Karnataka Shakti Scheme").shortTitle("SHAKTI")
                    .description("Free travel for all women on non-AC KSRTC/BMTC/NEKRTC/NWKRTC buses across Karnataka.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Women", "Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("bus", "travel", "women", "free", "ksrtc", "karnataka"))
                    .priority(1)
                    .benefitAmount("Free unlimited bus travel").benefitType("Service")
                    .minAge(0).maxAge(null).gender("Female").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://sevasindhu.karnataka.gov.in/").helpline("1800-425-1663")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH012"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH012").slug("gruha-jyoti")
                    .name("Karnataka Gruha Jyoti Scheme").shortTitle("GRUHA JYOTI")
                    .description("Free electricity up to 200 units per month for all domestic households in Karnataka.")
                    .level("State").schemeFor("Family")
                    .schemeCategory(List.of("Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("electricity", "free units", "karnataka", "domestic", "escom", "bescom"))
                    .priority(1)
                    .benefitAmount("200 units free/month (~₹1,000 saving)").benefitType("Utility Subsidy")
                    .minAge(18).maxAge(null).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://sevasindhu.karnataka.gov.in/").helpline("1912")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH013"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH013").slug("anna-bhagya")
                    .name("Karnataka Anna Bhagya Scheme").shortTitle("ANNA BHAGYA")
                    .description("Free rice distribution — 10 kg per person per month — to BPL families through ration shops.")
                    .level("State").schemeFor("Family")
                    .schemeCategory(List.of("Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("food", "rice", "ration", "bpl", "karnataka", "pds"))
                    .priority(1)
                    .benefitAmount("10 kg free rice/person/month").benefitType("Food Subsidy")
                    .minAge(0).maxAge(null).gender("All").maxIncome(null)
                    .eligibleCategories(List.of("SC", "ST")).requiresBpl(true).requiresDisability(false)
                    .officialWebsite("https://ahara.kar.nic.in/").helpline("1967")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH014"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH014").slug("yuva-nidhi")
                    .name("Karnataka Yuva Nidhi Scheme").shortTitle("YUVA NIDHI")
                    .description("Monthly unemployment allowance for educated unemployed youth in Karnataka for up to 2 years.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Education", "Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("youth", "unemployment", "degree", "diploma", "allowance", "karnataka"))
                    .priority(1)
                    .benefitAmount("₹3,000/month (degree) or ₹1,500/month (diploma)").benefitType("Allowance")
                    .minAge(18).maxAge(35).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://sevasindhu.karnataka.gov.in/").helpline("1800-5999-918")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH015"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH015").slug("rgrhcl")
                    .name("Rajiv Gandhi Housing Scheme (RGRHCL)").shortTitle("RGRHCL")
                    .description("Free pucca housing for homeless BPL families in Karnataka.")
                    .level("State").schemeFor("Family")
                    .schemeCategory(List.of("Housing"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("housing", "house", "bpl", "karnataka", "rural", "rgrhcl"))
                    .priority(1)
                    .benefitAmount("₹1.75 lakh for house construction").benefitType("Subsidy")
                    .minAge(18).maxAge(null).gender("All").maxIncome(120000.0)
                    .eligibleCategories(List.of("SC", "ST", "OBC")).requiresBpl(true).requiresDisability(false)
                    .officialWebsite("https://rgrhcl.kar.nic.in/").helpline("080-22032058")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH016"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH016").slug("raitha-shakti")
                    .name("Karnataka Raitha Shakti Yojana").shortTitle("RAITHA SHAKTI")
                    .description("Diesel subsidy for farmers to run farm equipment and irrigation pumps in Karnataka.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Agriculture"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("farmer", "diesel", "subsidy", "karnataka", "irrigation", "kisan"))
                    .priority(2)
                    .benefitAmount("Diesel subsidy (variable)").benefitType("Subsidy")
                    .minAge(18).maxAge(null).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .occupation("Farmer")
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://raitamitra.karnataka.gov.in/").helpline("155333")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH017"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH017").slug("bhagyalakshmi")
                    .name("Karnataka Bhagyalakshmi Scheme").shortTitle("BHAGYALAKSHMI")
                    .description("Financial support for girl child at birth and Rs 1 lakh bond on attaining 18 years, to prevent female foeticide.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Women", "Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("girl child", "birth", "karnataka", "bpl", "women", "bond"))
                    .priority(1)
                    .benefitAmount("₹19,300 at birth + ₹1,00,097 at age 18").benefitType("Cash Transfer")
                    .minAge(0).maxAge(0).gender("Female").maxIncome(200000.0)
                    .eligibleCategories(List.of("SC", "ST", "OBC")).requiresBpl(true).requiresDisability(false)
                    .officialWebsite("https://wcdkarnataka.gov.in/").helpline("080-22355984")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH018"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH018").slug("anila-bhagya")
                    .name("Karnataka Mukhyamantri Anila Bhagya Scheme").shortTitle("ANILA BHAGYA")
                    .description("Free LPG gas connection, stove and first refill for BPL families in Karnataka.")
                    .level("State").schemeFor("Family")
                    .schemeCategory(List.of("Women", "Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("lpg", "gas", "bpl", "karnataka", "women", "cooking fuel"))
                    .priority(2)
                    .benefitAmount("₹2,000 (free connection + stove + first refill)").benefitType("Subsidy")
                    .minAge(18).maxAge(null).gender("Female").maxIncome(120000.0)
                    .eligibleCategories(List.of("SC", "ST")).requiresBpl(true).requiresDisability(false)
                    .officialWebsite("https://sevasindhu.karnataka.gov.in/").helpline("1906")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH019"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH019").slug("gruha-arogya")
                    .name("Gruha Arogya Scheme Karnataka").shortTitle("GRUHA AROGYA")
                    .description("Free doorstep health screening and medicines for citizens across Karnataka by mobile health teams.")
                    .level("State").schemeFor("Family")
                    .schemeCategory(List.of("Health"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("health", "doorstep", "medicines", "karnataka", "screening", "free"))
                    .priority(1)
                    .benefitAmount("Free health check-up + medicines").benefitType("Healthcare Service")
                    .minAge(0).maxAge(null).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://karunadu.karnataka.gov.in/hfw/").helpline("104")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH020"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH020").slug("arivu")
                    .name("Karnataka Arivu Education Loan Scheme").shortTitle("ARIVU")
                    .description("Subsidised education loan for SC/ST students in Karnataka for higher and professional education.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Education", "Finance"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("education loan", "sc", "st", "karnataka", "higher education", "subsidy"))
                    .priority(1)
                    .benefitAmount("Loan up to ₹10 lakh at 0-2% interest").benefitType("Loan Subsidy")
                    .minAge(18).maxAge(35).gender("All").maxIncome(250000.0)
                    .eligibleCategories(List.of("SC", "ST"))
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://kscstdc.karnataka.gov.in/").helpline("080-22253370")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH021"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH021").slug("sarathi")
                    .name("Karnataka Swavalambi Sarathi Scheme").shortTitle("SARATHI")
                    .description("Vehicle subsidy for minorities to buy auto-rickshaw, taxi or goods vehicle for livelihood.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Finance", "Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("auto", "vehicle", "minority", "subsidy", "karnataka", "livelihood"))
                    .priority(2)
                    .benefitAmount("Subsidy up to ₹1 lakh on vehicle purchase").benefitType("Subsidy")
                    .minAge(21).maxAge(55).gender("All").maxIncome(600000.0)
                    .eligibleCategories(List.of("MINORITY"))
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://kmdcl.karnataka.gov.in/").helpline("080-22253500")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH022"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH022").slug("janasevaka")
                    .name("Karnataka Janasevaka Scheme").shortTitle("JANASEVAKA")
                    .description("Government certificates and services delivered at doorstep for citizens of Bengaluru Urban district.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("doorstep", "certificate", "bbmp", "bengaluru", "government service"))
                    .priority(3)
                    .benefitAmount("₹65 service charge — certificates at home").benefitType("Service")
                    .minAge(18).maxAge(null).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://bbmp.gov.in/").helpline("080-22660000")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH023"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH023").slug("prabuddha")
                    .name("Karnataka Prabuddha Overseas Scholarship").shortTitle("PRABUDDHA")
                    .description("Full scholarship for SC students from Karnataka to pursue Masters or PhD at top foreign universities.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Education"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("overseas scholarship", "sc", "masters", "phd", "abroad", "karnataka"))
                    .priority(1)
                    .benefitAmount("Full funding up to ₹25 lakh/year").benefitType("Scholarship")
                    .minAge(21).maxAge(40).gender("All").maxIncome(800000.0)
                    .eligibleCategories(List.of("SC"))
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://kscdc.net/").helpline("080-22253370")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH024"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH024").slug("ganga-kalyana")
                    .name("Karnataka Ganga Kalyana Scheme").shortTitle("GANGA KALYANA")
                    .description("Borewell and pump set subsidy for small and marginal minority community farmers for irrigation.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Agriculture", "Finance"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("borewell", "irrigation", "minority", "farmer", "karnataka", "subsidy"))
                    .priority(2)
                    .benefitAmount("Subsidy up to ₹1.5 lakh").benefitType("Subsidy")
                    .minAge(18).maxAge(65).gender("All").maxIncome(200000.0)
                    .eligibleCategories(List.of("MINORITY"))
                    .occupation("Farmer")
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://kmdcl.karnataka.gov.in/").helpline("080-22253500")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH025"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH025").slug("surya-ghar")
                    .name("Surya Ghar Muft Bijli Yojana").shortTitle("SURYA GHAR")
                    .description("Free rooftop solar panels for households — subsidy up to Rs 78,000 to generate free electricity and reduce bills.")
                    .level("Central").schemeFor("Family")
                    .schemeCategory(List.of("Social Welfare", "Finance"))
                    .beneficiaryState(List.of())
                    .tags(List.of("solar", "rooftop", "electricity", "subsidy", "renewable energy"))
                    .priority(2)
                    .benefitAmount("Subsidy up to ₹78,000 for 3kW solar").benefitType("Subsidy")
                    .minAge(18).maxAge(null).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://pmsuryaghar.gov.in/").helpline("1800-180-3333")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH026"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH026").slug("pm-poshan")
                    .name("PM POSHAN Scheme (Mid-Day Meal)").shortTitle("PM POSHAN")
                    .description("Free nutritious mid-day meals for children in government and government-aided schools (Classes 1-8).")
                    .level("Central").schemeFor("Individual")
                    .schemeCategory(List.of("Education", "Health"))
                    .beneficiaryState(List.of())
                    .tags(List.of("mid-day meal", "school", "children", "nutrition", "free meal"))
                    .priority(2)
                    .benefitAmount("Free cooked meal every school day").benefitType("Food Benefit")
                    .minAge(5).maxAge(14).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://pmposhan.education.gov.in/").helpline("1800-180-8004")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH027"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH027").slug("apy")
                    .name("Atal Pension Yojana").shortTitle("APY")
                    .description("Guaranteed pension scheme for unorganised sector workers providing Rs 1,000-5,000/month after age 60.")
                    .level("Central").schemeFor("Individual")
                    .schemeCategory(List.of("Finance", "Social Welfare"))
                    .beneficiaryState(List.of())
                    .tags(List.of("pension", "retirement", "unorganised sector", "old age", "pfrda"))
                    .priority(2)
                    .benefitAmount("₹1,000-5,000/month pension after 60").benefitType("Pension")
                    .minAge(18).maxAge(40).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://npscra.nsdl.co.in/scheme-details.php").helpline("1800-110-069")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH028"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH028").slug("st-marriage")
                    .name("Karnataka ST Marriage Assistance Scheme").shortTitle("ST MARRIAGE AID")
                    .description("Financial assistance of Rs 50,000 for marriage of Scheduled Tribe brides in Karnataka.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Women", "Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("st", "marriage", "bride", "karnataka", "tribal", "financial assistance"))
                    .priority(2)
                    .benefitAmount("₹50,000 one-time").benefitType("Cash Transfer")
                    .minAge(18).maxAge(35).gender("Female").maxIncome(200000.0)
                    .eligibleCategories(List.of("ST"))
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://stwelfare.karnataka.gov.in/").helpline("080-22261789")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH029"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH029").slug("kcc")
                    .name("Kisan Credit Card Scheme").shortTitle("KCC")
                    .description("Short-term credit up to Rs 3 lakh at 4% interest for farmers for agriculture and allied activities.")
                    .level("Central").schemeFor("Individual")
                    .schemeCategory(List.of("Agriculture", "Finance"))
                    .beneficiaryState(List.of())
                    .tags(List.of("kisan", "credit", "farmer", "loan", "nabard", "agriculture"))
                    .priority(1)
                    .benefitAmount("Credit up to ₹3 lakh at 4% interest").benefitType("Credit Facility")
                    .minAge(18).maxAge(75).gender("All").maxIncome(null)
                    .eligibleCategories(List.of())
                    .occupation("Farmer")
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://www.nabard.org/").helpline("022-26539895")
                    .active(true).build());

        if (!schemeRepo.existsById("SCH030"))
            schemeRepo.save(Scheme.builder()
                    .id("SCH030").slug("sc-widow-remarriage")
                    .name("Karnataka SC Widow Re-Marriage Assistance Scheme").shortTitle("SC WIDOW AID")
                    .description("Financial assistance of Rs 3 lakh for widows from Scheduled Caste community who remarry in Karnataka.")
                    .level("State").schemeFor("Individual")
                    .schemeCategory(List.of("Women", "Social Welfare"))
                    .beneficiaryState(List.of("Karnataka"))
                    .tags(List.of("widow", "sc", "remarriage", "karnataka", "financial assistance"))
                    .priority(2)
                    .benefitAmount("₹3 lakh one-time").benefitType("Cash Transfer")
                    .minAge(18).maxAge(50).gender("Female").maxIncome(200000.0)
                    .eligibleCategories(List.of("SC"))
                    .requiresBpl(false).requiresDisability(false)
                    .officialWebsite("https://www.karnataka.gov.in/").helpline("080-22261789")
                    .active(true).build());

        log.info("Schemes seeded. Total in DB: {}", schemeRepo.count());
    }

    // ─────────────────────────────────────────────────────────────────────────
    // PROJECTS — unchanged from original, all 60 projects preserved
    // ─────────────────────────────────────────────────────────────────────────
    private void seedProjects() {
        log.info("Seeding projects (skipping existing)...");

        if (!projectRepo.existsById("PRJ001"))
            projectRepo.save(Project.builder().id("PRJ001").name("PMGSY Rural Road - Hanumanamatti to Hubli Main")
                    .category("ROAD").description("Construction of 5.2 km all-weather road under PMGSY.")
                    .location("Hanumanamatti").pincode("581115").district("Haveri").state("Karnataka")
                    .budgetAllocated(8500000.0).budgetSpent(5100000.0)
                    .status("IN_PROGRESS").completionPercentage(60)
                    .startDate("2024-06-15").expectedCompletionDate("2025-03-30")
                    .sanctioningAuthority("PMGSY - Ministry of Rural Development")
                    .contractor("M/s Shree Constructions Pvt Ltd").sourceLink("https://omms.nic.in/").build());

        if (!projectRepo.existsById("PRJ002"))
            projectRepo.save(Project.builder().id("PRJ002").name("Anganwadi Centre Construction - Hanumanamatti")
                    .category("WOMEN").description("New Anganwadi centre with kitchen, play area, and toilet facilities.")
                    .location("Hanumanamatti").pincode("581115").district("Haveri").state("Karnataka")
                    .budgetAllocated(1200000.0).budgetSpent(1200000.0)
                    .status("COMPLETED").completionPercentage(100)
                    .startDate("2023-08-10").expectedCompletionDate("2024-02-28")
                    .sanctioningAuthority("Ministry of Women & Child Development")
                    .contractor("Karnataka State Construction Dept").sourceLink("https://wcd.nic.in/").build());

        if (!projectRepo.existsById("PRJ003"))
            projectRepo.save(Project.builder().id("PRJ003").name("Primary Health Centre Upgrade - Hanumanamatti")
                    .category("HEALTH").description("Upgrading PHC with 10 beds and maternity ward.")
                    .location("Hanumanamatti").pincode("581115").district("Haveri").state("Karnataka")
                    .budgetAllocated(3500000.0).budgetSpent(800000.0)
                    .status("DELAYED").completionPercentage(23)
                    .startDate("2024-01-20").expectedCompletionDate("2024-10-31")
                    .sanctioningAuthority("National Health Mission")
                    .contractor("M/s Karnataka Health Infra").sourceLink("https://nhm.gov.in/").build());

        if (!projectRepo.existsById("PRJ004"))
            projectRepo.save(Project.builder().id("PRJ004").name("Jal Jeevan Mission - Tap Water - Hanumanamatti")
                    .category("WATER").description("Piped water supply to 450 households in the village.")
                    .location("Hanumanamatti").pincode("581115").district("Haveri").state("Karnataka")
                    .budgetAllocated(4500000.0).budgetSpent(3600000.0)
                    .status("IN_PROGRESS").completionPercentage(78)
                    .startDate("2024-04-01").expectedCompletionDate("2025-01-15")
                    .sanctioningAuthority("Jal Jeevan Mission").contractor("Hubli Water Works Pvt Ltd")
                    .sourceLink("https://jaljeevanmission.gov.in/").build());

        if (!projectRepo.existsById("PRJ005"))
            projectRepo.save(Project.builder().id("PRJ005").name("PMAY-G Housing - Hanumanamatti BPL Families")
                    .category("HOUSING").description("Construction of 45 pucca houses for BPL families.")
                    .location("Hanumanamatti").pincode("581115").district("Haveri").state("Karnataka")
                    .budgetAllocated(6750000.0).budgetSpent(4200000.0)
                    .status("IN_PROGRESS").completionPercentage(62)
                    .startDate("2024-02-15").expectedCompletionDate("2024-12-31")
                    .sanctioningAuthority("PMAY-G Ministry of Rural Development")
                    .contractor("Beneficiary-led construction").sourceLink("https://pmayg.nic.in/").build());

        if (!projectRepo.existsById("PRJ006"))
            projectRepo.save(Project.builder().id("PRJ006").name("Government Primary School Renovation - Hanumanamatti")
                    .category("SCHOOL").description("Renovation of school, new toilets, boundary wall, mid-day meal kitchen.")
                    .location("Hanumanamatti").pincode("581115").district("Haveri").state("Karnataka")
                    .budgetAllocated(1800000.0).budgetSpent(450000.0)
                    .status("IN_PROGRESS").completionPercentage(25)
                    .startDate("2024-07-01").expectedCompletionDate("2025-02-28")
                    .sanctioningAuthority("Samagra Shiksha - Ministry of Education")
                    .contractor("M/s Educate India Builders").sourceLink("https://samagra.education.gov.in/").build());

        if (!projectRepo.existsById("PRJ007"))
            projectRepo.save(Project.builder().id("PRJ007").name("Solar Street Lighting - Hanumanamatti")
                    .category("ELECTRICITY").description("Installation of 85 solar-powered LED street lights.")
                    .location("Hanumanamatti").pincode("581115").district("Haveri").state("Karnataka")
                    .budgetAllocated(1275000.0).budgetSpent(1275000.0)
                    .status("COMPLETED").completionPercentage(100)
                    .startDate("2024-03-10").expectedCompletionDate("2024-05-30")
                    .sanctioningAuthority("MNRE - Ministry of New & Renewable Energy")
                    .contractor("SolarTech Karnataka").sourceLink("https://mnre.gov.in/").build());

        if (!projectRepo.existsById("PRJ008"))
            projectRepo.save(Project.builder().id("PRJ008").name("MGNREGA Farm Pond Excavation - Hanumanamatti")
                    .category("AGRICULTURE").description("25 farm ponds for water harvesting under MGNREGA.")
                    .location("Hanumanamatti").pincode("581115").district("Haveri").state("Karnataka")
                    .budgetAllocated(1875000.0).budgetSpent(1500000.0)
                    .status("IN_PROGRESS").completionPercentage(80)
                    .startDate("2024-05-01").expectedCompletionDate("2024-11-30")
                    .sanctioningAuthority("MGNREGA - Ministry of Rural Development")
                    .contractor("Community labor - GP supervised").sourceLink("https://nrega.nic.in/").build());

        // Projects PRJ009-PRJ060 follow the exact same pattern — all preserved from original DataSeeder.
        // For brevity they are included below as-is (identical to the original file).

        if (!projectRepo.existsById("PRJ009"))
            projectRepo.save(Project.builder().id("PRJ009").name("Namma Metro Phase 2A - Silk Board to KR Puram")
                    .category("TRANSPORT").description("14.5 km elevated metro corridor connecting IT hubs Silk Board to KR Puram via HSR Layout.")
                    .location("Bengaluru").pincode("560034").district("Bengaluru Urban").state("Karnataka")
                    .budgetAllocated(427000000000.0).budgetSpent(280000000000.0)
                    .status("IN_PROGRESS").completionPercentage(65)
                    .startDate("2020-01-01").expectedCompletionDate("2026-03-31")
                    .sanctioningAuthority("BMRCL / Ministry of Housing & Urban Affairs")
                    .contractor("Afcons Infrastructure Ltd").sourceLink("https://bmrc.co.in/").build());

        if (!projectRepo.existsById("PRJ010"))
            projectRepo.save(Project.builder().id("PRJ010").name("Bengaluru Outer Ring Road Elevated Corridor + Metro")
                    .category("TRANSPORT").description("32.15 km double-decker flyover with metro line along ORR to ease traffic congestion in Bengaluru.")
                    .location("Bengaluru").pincode("560037").district("Bengaluru Urban").state("Karnataka")
                    .budgetAllocated(1800000000000.0).budgetSpent(50000000000.0)
                    .status("PLANNING").completionPercentage(5)
                    .startDate("2025-01-01").expectedCompletionDate("2030-12-31")
                    .sanctioningAuthority("Karnataka Government / BBMP")
                    .contractor("TBD - Under Tender").sourceLink("https://bbmp.gov.in/").build());

        if (!projectRepo.existsById("PRJ011"))
            projectRepo.save(Project.builder().id("PRJ011").name("Bengaluru Smart City - Whitefield Area Development")
                    .category("URBAN").description("Integrated smart city infrastructure — roads, drainage, smart poles, free WiFi, CCTV in Whitefield.")
                    .location("Whitefield, Bengaluru").pincode("560066").district("Bengaluru Urban").state("Karnataka")
                    .budgetAllocated(2500000000.0).budgetSpent(1800000000.0)
                    .status("IN_PROGRESS").completionPercentage(72)
                    .startDate("2022-04-01").expectedCompletionDate("2025-09-30")
                    .sanctioningAuthority("Smart Cities Mission / BBMP / BESCOM")
                    .contractor("L&T Infrastructure Engineering").sourceLink("https://smartcities.gov.in/").build());

        if (!projectRepo.existsById("PRJ012"))
            projectRepo.save(Project.builder().id("PRJ012").name("Devanahalli Business Park (IT Park)")
                    .category("INDUSTRY").description("407-acre world-class IT and startup business park near Devanahalli, Bengaluru.")
                    .location("Devanahalli").pincode("562110").district("Bengaluru Rural").state("Karnataka")
                    .budgetAllocated(30000000000.0).budgetSpent(8000000000.0)
                    .status("IN_PROGRESS").completionPercentage(28)
                    .startDate("2022-09-01").expectedCompletionDate("2027-12-31")
                    .sanctioningAuthority("KIADB / Karnataka Industries Department")
                    .contractor("KIADB (Karnataka Industrial Areas Development Board)").sourceLink("https://kiadb.in/").build());

        if (!projectRepo.existsById("PRJ013"))
            projectRepo.save(Project.builder().id("PRJ013").name("Mysuru-Kushalnagar NH-275 4-Lane Widening")
                    .category("ROAD").description("Widening of NH-275 to 4 lanes from Mysuru to Kushalnagar for 85 km.")
                    .location("Mysuru").pincode("570001").district("Mysuru").state("Karnataka")
                    .budgetAllocated(32000000000.0).budgetSpent(12000000000.0)
                    .status("IN_PROGRESS").completionPercentage(38)
                    .startDate("2023-03-15").expectedCompletionDate("2026-09-30")
                    .sanctioningAuthority("NHAI / Ministry of Road Transport & Highways")
                    .contractor("GR Infraprojects Ltd").sourceLink("https://nhai.gov.in/").build());

        if (!projectRepo.existsById("PRJ014"))
            projectRepo.save(Project.builder().id("PRJ014").name("Mysuru New Town Water Supply Scheme")
                    .category("WATER").description("New water treatment plant and pipeline network to supply 24x7 safe drinking water to Mysuru city.")
                    .location("Mysuru").pincode("570001").district("Mysuru").state("Karnataka")
                    .budgetAllocated(4200000000.0).budgetSpent(2100000000.0)
                    .status("IN_PROGRESS").completionPercentage(50)
                    .startDate("2023-07-01").expectedCompletionDate("2025-12-31")
                    .sanctioningAuthority("AMRUT 2.0 / Karnataka Urban Water Supply & Drainage Board")
                    .contractor("SPML Infra Ltd").sourceLink("https://amrut.gov.in/").build());

        if (!projectRepo.existsById("PRJ015"))
            projectRepo.save(Project.builder().id("PRJ015").name("Mysuru Government Medical College Hospital Upgrade")
                    .category("HEALTH").description("Expansion of MMC&RI hospital — new 500-bed block, ICU, trauma centre and modern OTs.")
                    .location("Mysuru").pincode("570001").district("Mysuru").state("Karnataka")
                    .budgetAllocated(8000000000.0).budgetSpent(2500000000.0)
                    .status("IN_PROGRESS").completionPercentage(31)
                    .startDate("2024-01-15").expectedCompletionDate("2027-06-30")
                    .sanctioningAuthority("National Health Mission / Karnataka Health Dept")
                    .contractor("Shapoorji Pallonji Construction").sourceLink("https://nhm.gov.in/").build());

        if (!projectRepo.existsById("PRJ016"))
            projectRepo.save(Project.builder().id("PRJ016").name("Sharavathi Bridge & NH Projects - Shivamogga")
                    .category("ROAD").description("9 NH projects including new Sharavathi Bridge to improve connectivity between Malnad and coastal regions.")
                    .location("Sagara, Shivamogga").pincode("577401").district("Shivamogga").state("Karnataka")
                    .budgetAllocated(2000000000.0).budgetSpent(1900000000.0)
                    .status("COMPLETED").completionPercentage(100)
                    .startDate("2022-04-01").expectedCompletionDate("2025-07-14")
                    .sanctioningAuthority("NHAI / Ministry of Road Transport & Highways")
                    .contractor("KCVR Infra Projects Pvt Ltd").sourceLink("https://nhai.gov.in/").build());

        if (!projectRepo.existsById("PRJ017"))
            projectRepo.save(Project.builder().id("PRJ017").name("Shivamogga Airport Terminal Expansion")
                    .category("TRANSPORT").description("Expansion of Shivamogga Airport terminal to handle increased passenger traffic.")
                    .location("Shivamogga").pincode("577201").district("Shivamogga").state("Karnataka")
                    .budgetAllocated(5000000000.0).budgetSpent(1200000000.0)
                    .status("IN_PROGRESS").completionPercentage(24)
                    .startDate("2024-04-01").expectedCompletionDate("2026-12-31")
                    .sanctioningAuthority("AAI / Ministry of Civil Aviation")
                    .contractor("KMB Infra Ltd").sourceLink("https://aai.aero/").build());

        if (!projectRepo.existsById("PRJ018"))
            projectRepo.save(Project.builder().id("PRJ018").name("Dharwad Smart City - City Core Redevelopment")
                    .category("URBAN").description("Redevelopment of Dharwad city core — underground cabling, heritage walks, storm water drains, smart parking.")
                    .location("Dharwad").pincode("580001").district("Dharwad").state("Karnataka")
                    .budgetAllocated(1800000000.0).budgetSpent(900000000.0)
                    .status("IN_PROGRESS").completionPercentage(50)
                    .startDate("2022-11-01").expectedCompletionDate("2025-10-31")
                    .sanctioningAuthority("Smart Cities Mission / Dharwad City Corporation")
                    .contractor("KEONICS / Uday Constructions").sourceLink("https://smartcities.gov.in/").build());

        if (!projectRepo.existsById("PRJ019"))
            projectRepo.save(Project.builder().id("PRJ019").name("Smart Classroom Setup - Govt Schools Dharwad")
                    .category("SCHOOL").description("Smart boards, projectors, computers and internet in 120 government schools in Dharwad district.")
                    .location("Dharwad").pincode("580001").district("Dharwad").state("Karnataka")
                    .budgetAllocated(240000000.0).budgetSpent(90000000.0)
                    .status("IN_PROGRESS").completionPercentage(38)
                    .startDate("2025-01-10").expectedCompletionDate("2025-08-31")
                    .sanctioningAuthority("Samagra Shiksha - Ministry of Education")
                    .contractor("DigiLearn Systems Pvt Ltd").sourceLink("https://samagra.education.gov.in/").build());

        if (!projectRepo.existsById("PRJ020"))
            projectRepo.save(Project.builder().id("PRJ020").name("Shiradi Ghat NH-75 Restoration Works")
                    .category("ROAD").description("Restoration and slope protection works on NH-75 Shiradi Ghat stretch for monsoon safety.")
                    .location("Shiradi Ghat").pincode("574328").district("Dakshina Kannada").state("Karnataka")
                    .budgetAllocated(3500000000.0).budgetSpent(2800000000.0)
                    .status("IN_PROGRESS").completionPercentage(80)
                    .startDate("2023-10-01").expectedCompletionDate("2025-06-30")
                    .sanctioningAuthority("NHAI / Ministry of Road Transport & Highways")
                    .contractor("G R Infraprojects Ltd").sourceLink("https://nhai.gov.in/").build());

        if (!projectRepo.existsById("PRJ021"))
            projectRepo.save(Project.builder().id("PRJ021").name("New Mangaluru Port Capacity Expansion")
                    .category("INDUSTRY").description("Expansion of New Mangaluru Port — new berths, mechanised coal handling plant, deep draft facility.")
                    .location("Mangaluru").pincode("575011").district("Dakshina Kannada").state("Karnataka")
                    .budgetAllocated(12000000000.0).budgetSpent(4000000000.0)
                    .status("IN_PROGRESS").completionPercentage(33)
                    .startDate("2023-06-01").expectedCompletionDate("2027-03-31")
                    .sanctioningAuthority("Ministry of Ports, Shipping & Waterways")
                    .contractor("Adani Ports & Special Economic Zone").sourceLink("https://nmpt.gov.in/").build());

        if (!projectRepo.existsById("PRJ022"))
            projectRepo.save(Project.builder().id("PRJ022").name("Bidar-Humnabad NH-367 4-Lane Widening")
                    .category("ROAD").description("Widening of 47 km Bidar-Humnabad section of NH-367 to 4 lanes.")
                    .location("Bidar").pincode("585401").district("Bidar").state("Karnataka")
                    .budgetAllocated(8500000000.0).budgetSpent(1200000000.0)
                    .status("IN_PROGRESS").completionPercentage(14)
                    .startDate("2025-01-01").expectedCompletionDate("2027-06-30")
                    .sanctioningAuthority("NHAI / Ministry of Road Transport & Highways")
                    .contractor("SRC Infra Developers Pvt Ltd").sourceLink("https://nhai.gov.in/").build());

        if (!projectRepo.existsById("PRJ023"))
            projectRepo.save(Project.builder().id("PRJ023").name("Bidar Jal Jeevan Mission - Rural Water Supply")
                    .category("WATER").description("Piped water connections to 89,000 rural households in Bidar district under Jal Jeevan Mission.")
                    .location("Bidar").pincode("585401").district("Bidar").state("Karnataka")
                    .budgetAllocated(9800000000.0).budgetSpent(6500000000.0)
                    .status("IN_PROGRESS").completionPercentage(66)
                    .startDate("2022-08-01").expectedCompletionDate("2025-09-30")
                    .sanctioningAuthority("Jal Jeevan Mission / Karnataka Rural Water Supply Dept")
                    .contractor("VA Tech Wabag Ltd").sourceLink("https://jaljeevanmission.gov.in/").build());

        if (!projectRepo.existsById("PRJ024"))
            projectRepo.save(Project.builder().id("PRJ024").name("Kalaburagi AIIMS - All India Institute of Medical Sciences")
                    .category("HEALTH").description("New AIIMS hospital campus with 750 beds, medical college, nursing college for North Karnataka.")
                    .location("Kalaburagi").pincode("585102").district("Kalaburagi").state("Karnataka")
                    .budgetAllocated(160000000000.0).budgetSpent(40000000000.0)
                    .status("IN_PROGRESS").completionPercentage(25)
                    .startDate("2022-01-15").expectedCompletionDate("2027-03-31")
                    .sanctioningAuthority("Ministry of Health & Family Welfare")
                    .contractor("Shapoorji Pallonji & Company").sourceLink("https://aiimskalyani.edu.in/").build());

        if (!projectRepo.existsById("PRJ025"))
            projectRepo.save(Project.builder().id("PRJ025").name("Kalaburagi District Irrigation - Upper Krishna Project")
                    .category("AGRICULTURE").description("Canal network completion under Upper Krishna Project Phase-III to irrigate 2.13 lakh acres in Kalaburagi district.")
                    .location("Kalaburagi").pincode("585101").district("Kalaburagi").state("Karnataka")
                    .budgetAllocated(48000000000.0).budgetSpent(28000000000.0)
                    .status("IN_PROGRESS").completionPercentage(58)
                    .startDate("2020-04-01").expectedCompletionDate("2026-03-31")
                    .sanctioningAuthority("Karnataka Neeravari Nigama Ltd / Jal Shakti Ministry")
                    .contractor("KNNL + Multiple Contractors").sourceLink("https://knnl.karnataka.gov.in/").build());

        if (!projectRepo.existsById("PRJ026"))
            projectRepo.save(Project.builder().id("PRJ026").name("Belagavi-Pune NH-48 Expressway")
                    .category("ROAD").description("6-lane access-controlled expressway connecting Bengaluru to Pune via Belagavi under Bharatmala Phase-II.")
                    .location("Belagavi").pincode("590001").district("Belagavi").state("Karnataka")
                    .budgetAllocated(193200000000.0).budgetSpent(30000000000.0)
                    .status("IN_PROGRESS").completionPercentage(16)
                    .startDate("2023-06-01").expectedCompletionDate("2028-12-31")
                    .sanctioningAuthority("NHAI - Bharatmala Pariyojana Phase-II")
                    .contractor("Multiple contractors - Packagewise").sourceLink("https://nhai.gov.in/").build());

        if (!projectRepo.existsById("PRJ027"))
            projectRepo.save(Project.builder().id("PRJ027").name("Belagavi Smart City - Central Business District")
                    .category("URBAN").description("Redevelopment of Belagavi CBD with underground utilities, heritage precincts, multi-level parking, smart surveillance.")
                    .location("Belagavi").pincode("590001").district("Belagavi").state("Karnataka")
                    .budgetAllocated(1600000000.0).budgetSpent(700000000.0)
                    .status("IN_PROGRESS").completionPercentage(44)
                    .startDate("2023-01-01").expectedCompletionDate("2026-03-31")
                    .sanctioningAuthority("Smart Cities Mission / Belagavi City Corporation")
                    .contractor("L&T Construction").sourceLink("https://smartcities.gov.in/").build());

        if (!projectRepo.existsById("PRJ028"))
            projectRepo.save(Project.builder().id("PRJ028").name("Tumkuru Industrial Township (TUDA)")
                    .category("INDUSTRY").description("2000-acre integrated industrial township near Tumkuru on NH-48 corridor.")
                    .location("Tumkuru").pincode("572101").district("Tumkuru").state("Karnataka")
                    .budgetAllocated(50000000000.0).budgetSpent(15000000000.0)
                    .status("IN_PROGRESS").completionPercentage(30)
                    .startDate("2021-09-01").expectedCompletionDate("2026-12-31")
                    .sanctioningAuthority("KIADB / DPIIT / National Industrial Corridor Prog")
                    .contractor("KIADB + Shapoorji Pallonji").sourceLink("https://kiadb.in/").build());

        if (!projectRepo.existsById("PRJ029"))
            projectRepo.save(Project.builder().id("PRJ029").name("Tumkuru Jal Jeevan Mission - Urban Water Supply")
                    .category("WATER").description("24x7 piped water supply to all 1.2 lakh households in Tumkuru city under AMRUT 2.0.")
                    .location("Tumkuru").pincode("572101").district("Tumkuru").state("Karnataka")
                    .budgetAllocated(5200000000.0).budgetSpent(2900000000.0)
                    .status("IN_PROGRESS").completionPercentage(55)
                    .startDate("2023-04-01").expectedCompletionDate("2025-12-31")
                    .sanctioningAuthority("AMRUT 2.0 / KUWSDB")
                    .contractor("SPML Infra Ltd").sourceLink("https://amrut.gov.in/").build());

        if (!projectRepo.existsById("PRJ030"))
            projectRepo.save(Project.builder().id("PRJ030").name("Bengaluru-Chennai Expressway (KGF to Hoskote Operational)")
                    .category("ROAD").description("6-lane access-controlled expressway. 68 km Hoskote-KGF section operational.")
                    .location("Bengaluru / Kolar").pincode("563118").district("Kolar").state("Karnataka")
                    .budgetAllocated(173000000000.0).budgetSpent(120000000000.0)
                    .status("IN_PROGRESS").completionPercentage(70)
                    .startDate("2020-07-01").expectedCompletionDate("2026-03-31")
                    .sanctioningAuthority("NHAI / Ministry of Road Transport & Highways")
                    .contractor("Dilip Buildcon + PNC Infratech").sourceLink("https://nhai.gov.in/").build());

        if (!projectRepo.existsById("PRJ031"))
            projectRepo.save(Project.builder().id("PRJ031").name("Vijayapura District Hospital Modernisation")
                    .category("HEALTH").description("Modernisation of Vijayapura District Government Hospital with new OT complex, ICU, NICU, lab and emergency block.")
                    .location("Vijayapura").pincode("586101").district("Vijayapura").state("Karnataka")
                    .budgetAllocated(2800000000.0).budgetSpent(800000000.0)
                    .status("IN_PROGRESS").completionPercentage(29)
                    .startDate("2024-03-01").expectedCompletionDate("2026-06-30")
                    .sanctioningAuthority("NHM / Karnataka Health & Family Welfare Dept")
                    .contractor("B.G. Shirke Construction Technology").sourceLink("https://nhm.gov.in/").build());

        if (!projectRepo.existsById("PRJ032"))
            projectRepo.save(Project.builder().id("PRJ032").name("Vijayapura Urban Flood Mitigation - Storm Water Drains")
                    .category("WATER").description("Construction of 48 km storm water drains and retention ponds to prevent urban flooding.")
                    .location("Vijayapura").pincode("586101").district("Vijayapura").state("Karnataka")
                    .budgetAllocated(1500000000.0).budgetSpent(600000000.0)
                    .status("IN_PROGRESS").completionPercentage(40)
                    .startDate("2024-06-01").expectedCompletionDate("2026-03-31")
                    .sanctioningAuthority("AMRUT 2.0 / Karnataka Urban Development Dept")
                    .contractor("Uday Constructions Pvt Ltd").sourceLink("https://amrut.gov.in/").build());

        if (!projectRepo.existsById("PRJ033"))
            projectRepo.save(Project.builder().id("PRJ033").name("Raichur RTPS Solar Park Extension")
                    .category("ELECTRICITY").description("500 MW solar power park extension at Raichur Thermal Power Station site.")
                    .location("Raichur").pincode("584101").district("Raichur").state("Karnataka")
                    .budgetAllocated(25000000000.0).budgetSpent(5000000000.0)
                    .status("IN_PROGRESS").completionPercentage(20)
                    .startDate("2024-09-01").expectedCompletionDate("2027-03-31")
                    .sanctioningAuthority("MNRE / KREDL / KPCL")
                    .contractor("Adani Green Energy / KPCL").sourceLink("https://kredl.kar.nic.in/").build());

        if (!projectRepo.existsById("PRJ034"))
            projectRepo.save(Project.builder().id("PRJ034").name("Raichur Narayanpura Canal Irrigation Revival")
                    .category("AGRICULTURE").description("Restoration and lining of 320 km canal network from Narayanpura dam to irrigate 1.5 lakh acres.")
                    .location("Raichur").pincode("584101").district("Raichur").state("Karnataka")
                    .budgetAllocated(12000000000.0).budgetSpent(7200000000.0)
                    .status("IN_PROGRESS").completionPercentage(60)
                    .startDate("2022-10-01").expectedCompletionDate("2025-09-30")
                    .sanctioningAuthority("Karnataka Neeravari Nigama Ltd")
                    .contractor("KNNL Direct").sourceLink("https://knnl.karnataka.gov.in/").build());

        if (!projectRepo.existsById("PRJ035"))
            projectRepo.save(Project.builder().id("PRJ035").name("Kodagu Flood Rehabilitation - Houses & Roads")
                    .category("HOUSING").description("Post-flood reconstruction of 2,500 houses and 180 km damaged rural roads in Kodagu.")
                    .location("Madikeri, Kodagu").pincode("571201").district("Kodagu").state("Karnataka")
                    .budgetAllocated(8500000000.0).budgetSpent(5000000000.0)
                    .status("IN_PROGRESS").completionPercentage(58)
                    .startDate("2022-03-01").expectedCompletionDate("2025-12-31")
                    .sanctioningAuthority("NDRF / SDRF / Karnataka Revenue Department")
                    .contractor("Multiple contractors + KPWD").sourceLink("https://ksdma.karnataka.gov.in/").build());

        if (!projectRepo.existsById("PRJ036"))
            projectRepo.save(Project.builder().id("PRJ036").name("Hassan District Solar-Powered Irrigation Pumps (KUSUM)")
                    .category("AGRICULTURE").description("Installation of 8,000 solar pumps for farmers in Hassan district under PM-KUSUM scheme.")
                    .location("Hassan").pincode("573201").district("Hassan").state("Karnataka")
                    .budgetAllocated(4000000000.0).budgetSpent(2400000000.0)
                    .status("IN_PROGRESS").completionPercentage(60)
                    .startDate("2023-06-01").expectedCompletionDate("2025-09-30")
                    .sanctioningAuthority("MNRE / PM-KUSUM / KREDL")
                    .contractor("Vikram Solar / KPCL empanelled vendors").sourceLink("https://pmkusum.mnre.gov.in/").build());

        if (!projectRepo.existsById("PRJ037"))
            projectRepo.save(Project.builder().id("PRJ037").name("Chikkamagaluru Eco-Tourism Circuit Development")
                    .category("TOURISM").description("Development of eco-tourism circuits linking Mullayanagiri, Kudremukh, Bhadra Wildlife — new trails, rest houses, visitor centres.")
                    .location("Chikkamagaluru").pincode("577101").district("Chikkamagaluru").state("Karnataka")
                    .budgetAllocated(800000000.0).budgetSpent(200000000.0)
                    .status("IN_PROGRESS").completionPercentage(25)
                    .startDate("2024-07-01").expectedCompletionDate("2026-06-30")
                    .sanctioningAuthority("Karnataka Tourism Dept / PRASAD Scheme / Ministry of Tourism")
                    .contractor("Karnataka State Tourism Development Corp").sourceLink("https://karnatakatourism.org/").build());

        if (!projectRepo.existsById("PRJ038"))
            projectRepo.save(Project.builder().id("PRJ038").name("Udupi Kundapur Coastal Road Development")
                    .category("ROAD").description("4-lane coastal highway development from Udupi to Kundapur with sea bridges and bypasses under Sagarmala.")
                    .location("Udupi").pincode("576101").district("Udupi").state("Karnataka")
                    .budgetAllocated(12000000000.0).budgetSpent(3500000000.0)
                    .status("IN_PROGRESS").completionPercentage(29)
                    .startDate("2023-09-01").expectedCompletionDate("2027-03-31")
                    .sanctioningAuthority("Sagarmala / NHAI / MoRTH")
                    .contractor("G R Infraprojects + Coastal Road Corp").sourceLink("https://sagarmala.gov.in/").build());

        if (!projectRepo.existsById("PRJ039"))
            projectRepo.save(Project.builder().id("PRJ039").name("Ballari Steel Plant Township Housing - SAIL")
                    .category("HOUSING").description("Construction of 3,200 affordable housing units for SAIL Ballari plant workers and BPL families.")
                    .location("Ballari").pincode("583101").district("Ballari").state("Karnataka")
                    .budgetAllocated(6500000000.0).budgetSpent(3200000000.0)
                    .status("IN_PROGRESS").completionPercentage(49)
                    .startDate("2022-11-01").expectedCompletionDate("2025-11-30")
                    .sanctioningAuthority("PMAY / SAIL / Ministry of Steel")
                    .contractor("NBCC India Ltd").sourceLink("https://pmay-urban.gov.in/").build());

        if (!projectRepo.existsById("PRJ040"))
            projectRepo.save(Project.builder().id("PRJ040").name("Gadag Wind Energy Expansion - Kappatagudda")
                    .category("ELECTRICITY").description("300 MW wind power project at Kappatagudda hills in Gadag district.")
                    .location("Gadag").pincode("582101").district("Gadag").state("Karnataka")
                    .budgetAllocated(18000000000.0).budgetSpent(4000000000.0)
                    .status("IN_PROGRESS").completionPercentage(22)
                    .startDate("2024-11-01").expectedCompletionDate("2027-06-30")
                    .sanctioningAuthority("MNRE / KREDL / Ministry of Power")
                    .contractor("Greenko Energy Holdings Pvt Ltd").sourceLink("https://kredl.kar.nic.in/").build());

        if (!projectRepo.existsById("PRJ041"))
            projectRepo.save(Project.builder().id("PRJ041").name("Vanivilas Reservoir Modernisation - Chitradurga")
                    .category("WATER").description("Modernisation and desilting of Vanivilas Sagar reservoir with improved canal network.")
                    .location("Chitradurga").pincode("577501").district("Chitradurga").state("Karnataka")
                    .budgetAllocated(6500000000.0).budgetSpent(2800000000.0)
                    .status("IN_PROGRESS").completionPercentage(43)
                    .startDate("2023-05-01").expectedCompletionDate("2026-03-31")
                    .sanctioningAuthority("Karnataka Neeravari Nigama Ltd / Jal Shakti Ministry")
                    .contractor("KNNL + Navayuga Engineering Company").sourceLink("https://knnl.karnataka.gov.in/").build());

        if (!projectRepo.existsById("PRJ042"))
            projectRepo.save(Project.builder().id("PRJ042").name("Chitradurga Fort Heritage Conservation & Tourism")
                    .category("TOURISM").description("Conservation and restoration of the 17th-century Chitradurga Fort with visitor amenities.")
                    .location("Chitradurga").pincode("577501").district("Chitradurga").state("Karnataka")
                    .budgetAllocated(450000000.0).budgetSpent(180000000.0)
                    .status("IN_PROGRESS").completionPercentage(40)
                    .startDate("2023-11-01").expectedCompletionDate("2025-10-31")
                    .sanctioningAuthority("Archaeological Survey of India / Karnataka Tourism Dept")
                    .contractor("Karnataka State Tourism Development Corp").sourceLink("https://asi.nic.in/").build());

        if (!projectRepo.existsById("PRJ043"))
            projectRepo.save(Project.builder().id("PRJ043").name("Davanagere Textile Park - Integrated Apparel Cluster")
                    .category("INDUSTRY").description("300-acre integrated textile and apparel manufacturing cluster at Davanagere.")
                    .location("Davanagere").pincode("577001").district("Davanagere").state("Karnataka")
                    .budgetAllocated(8000000000.0).budgetSpent(2000000000.0)
                    .status("IN_PROGRESS").completionPercentage(25)
                    .startDate("2024-03-01").expectedCompletionDate("2027-09-30")
                    .sanctioningAuthority("Ministry of Textiles / KIADB / Karnataka Industries Dept")
                    .contractor("KIADB + Arvind Infrastructure Ltd").sourceLink("https://kiadb.in/").build());

        if (!projectRepo.existsById("PRJ044"))
            projectRepo.save(Project.builder().id("PRJ044").name("Davanagere AMRUT 2.0 - Sewage Treatment Plant")
                    .category("WATER").description("New 60 MLD sewage treatment plant and underground sewerage network in Davanagere city.")
                    .location("Davanagere").pincode("577001").district("Davanagere").state("Karnataka")
                    .budgetAllocated(3200000000.0).budgetSpent(960000000.0)
                    .status("IN_PROGRESS").completionPercentage(30)
                    .startDate("2024-02-01").expectedCompletionDate("2026-08-31")
                    .sanctioningAuthority("AMRUT 2.0 / Karnataka Urban Development Dept")
                    .contractor("VA Tech Wabag Ltd").sourceLink("https://amrut.gov.in/").build());

        if (!projectRepo.existsById("PRJ045"))
            projectRepo.save(Project.builder().id("PRJ045").name("Koppal Solar Energy Park - 2000 MW")
                    .category("ELECTRICITY").description("Ultra Mega Solar Power Park at Shapur, Koppal — one of the largest in Karnataka.")
                    .location("Shapur, Koppal").pincode("583231").district("Koppal").state("Karnataka")
                    .budgetAllocated(100000000000.0).budgetSpent(35000000000.0)
                    .status("IN_PROGRESS").completionPercentage(35)
                    .startDate("2022-07-01").expectedCompletionDate("2026-12-31")
                    .sanctioningAuthority("MNRE / KREDL / SECI")
                    .contractor("Adani Green Energy + ReNew Power").sourceLink("https://kredl.kar.nic.in/").build());

        if (!projectRepo.existsById("PRJ046"))
            projectRepo.save(Project.builder().id("PRJ046").name("Koppal District Hospital Expansion")
                    .category("HEALTH").description("New 300-bed block with ICU, dialysis unit, blood bank and modern diagnostic centre at Koppal District Hospital.")
                    .location("Koppal").pincode("583231").district("Koppal").state("Karnataka")
                    .budgetAllocated(1800000000.0).budgetSpent(450000000.0)
                    .status("IN_PROGRESS").completionPercentage(25)
                    .startDate("2024-06-01").expectedCompletionDate("2026-12-31")
                    .sanctioningAuthority("NHM / Karnataka Health & Family Welfare Dept")
                    .contractor("Ahluwalia Contracts India Ltd").sourceLink("https://nhm.gov.in/").build());

        if (!projectRepo.existsById("PRJ047"))
            projectRepo.save(Project.builder().id("PRJ047").name("Yadgir Jal Jeevan Mission - Multi Village Water Supply")
                    .category("WATER").description("Multi-village rural water supply scheme covering 320 villages in Yadgir district.")
                    .location("Yadgir").pincode("585201").district("Yadgir").state("Karnataka")
                    .budgetAllocated(12500000000.0).budgetSpent(7500000000.0)
                    .status("IN_PROGRESS").completionPercentage(60)
                    .startDate("2022-04-01").expectedCompletionDate("2025-12-31")
                    .sanctioningAuthority("Jal Jeevan Mission / Karnataka Rural Water Supply Dept")
                    .contractor("Megha Engineering & Infrastructures Ltd").sourceLink("https://jaljeevanmission.gov.in/").build());

        if (!projectRepo.existsById("PRJ048"))
            projectRepo.save(Project.builder().id("PRJ048").name("Yadgir Model Residential School (Morarji Desai)")
                    .category("SCHOOL").description("New Morarji Desai Residential School campus with 500 student capacity for SC/ST students.")
                    .location("Yadgir").pincode("585201").district("Yadgir").state("Karnataka")
                    .budgetAllocated(600000000.0).budgetSpent(420000000.0)
                    .status("IN_PROGRESS").completionPercentage(70)
                    .startDate("2023-09-01").expectedCompletionDate("2025-06-30")
                    .sanctioningAuthority("Karnataka SC/ST Welfare Dept / Ekalavya Model School Scheme")
                    .contractor("Karnataka State Construction Corp").sourceLink("https://sswkarnataka.ac.in/").build());

        if (!projectRepo.existsById("PRJ049"))
            projectRepo.save(Project.builder().id("PRJ049").name("Chamarajanagar PMAY-G Tribal Housing - Soliga Community")
                    .category("HOUSING").description("Construction of 3,800 pucca houses for Soliga and other forest-dwelling tribal communities.")
                    .location("Chamarajanagar").pincode("571313").district("Chamarajanagar").state("Karnataka")
                    .budgetAllocated(5700000000.0).budgetSpent(3420000000.0)
                    .status("IN_PROGRESS").completionPercentage(60)
                    .startDate("2022-10-01").expectedCompletionDate("2025-09-30")
                    .sanctioningAuthority("PMAY-G / Ministry of Tribal Affairs / Ministry of Rural Development")
                    .contractor("Beneficiary-led construction supervised by GP").sourceLink("https://pmayg.nic.in/").build());

        if (!projectRepo.existsById("PRJ050"))
            projectRepo.save(Project.builder().id("PRJ050").name("Biligirirangaswamy Temple Wildlife Sanctuary - Eco-Tourism")
                    .category("TOURISM").description("Sustainable eco-tourism infrastructure at BRT Wildlife Sanctuary with nature trails and tribal cultural centre.")
                    .location("Chamarajanagar").pincode("571441").district("Chamarajanagar").state("Karnataka")
                    .budgetAllocated(350000000.0).budgetSpent(105000000.0)
                    .status("IN_PROGRESS").completionPercentage(30)
                    .startDate("2024-04-01").expectedCompletionDate("2026-03-31")
                    .sanctioningAuthority("Karnataka Forest Dept / Karnataka Tourism Dept")
                    .contractor("Karnataka State Forest Development Corp").sourceLink("https://karnatakatourism.org/").build());

        if (!projectRepo.existsById("PRJ051"))
            projectRepo.save(Project.builder().id("PRJ051").name("KRS Dam Strengthening & Cauvery Water Supply Improvement")
                    .category("WATER").description("Structural strengthening of Krishnarajasagara Dam and modernisation of water distribution for Mandya, Mysuru and Bengaluru.")
                    .location("Mandya").pincode("571401").district("Mandya").state("Karnataka")
                    .budgetAllocated(7500000000.0).budgetSpent(3000000000.0)
                    .status("IN_PROGRESS").completionPercentage(40)
                    .startDate("2023-08-01").expectedCompletionDate("2026-09-30")
                    .sanctioningAuthority("Karnataka Cauvery Neeravari Nigama / Jal Shakti")
                    .contractor("Navayuga Engineering Co + KNNL").sourceLink("https://knnl.karnataka.gov.in/").build());

        if (!projectRepo.existsById("PRJ052"))
            projectRepo.save(Project.builder().id("PRJ052").name("Mandya Sugar Industry Modernisation - MYSORE SUGAR")
                    .category("INDUSTRY").description("Expansion and modernisation of Mysore Sugar Company — new 5,000 TCD plant, ethanol distillery and co-generation power plant.")
                    .location("Mandya").pincode("571401").district("Mandya").state("Karnataka")
                    .budgetAllocated(3500000000.0).budgetSpent(1750000000.0)
                    .status("IN_PROGRESS").completionPercentage(50)
                    .startDate("2023-11-01").expectedCompletionDate("2025-10-31")
                    .sanctioningAuthority("Karnataka Cooperative Societies Dept / Ministry of Food Processing")
                    .contractor("Triveni Engineering & Industries Ltd").sourceLink("https://www.karnataka.gov.in/").build());

        if (!projectRepo.existsById("PRJ053"))
            projectRepo.save(Project.builder().id("PRJ053").name("Almatti Dam Backwater Area Irrigation Expansion")
                    .category("AGRICULTURE").description("Extension of irrigation canals from Almatti Reservoir to bring additional 3 lakh acres under irrigation.")
                    .location("Bagalkot").pincode("587101").district("Bagalkot").state("Karnataka")
                    .budgetAllocated(38000000000.0).budgetSpent(15200000000.0)
                    .status("IN_PROGRESS").completionPercentage(40)
                    .startDate("2021-06-01").expectedCompletionDate("2026-06-30")
                    .sanctioningAuthority("Upper Krishna Project Authority / KNNL / Jal Shakti")
                    .contractor("KNNL + Ramky Infrastructure").sourceLink("https://knnl.karnataka.gov.in/").build());

        if (!projectRepo.existsById("PRJ054"))
            projectRepo.save(Project.builder().id("PRJ054").name("Badami-Pattadakal-Aihole Heritage Corridor")
                    .category("TOURISM").description("Integrated heritage tourism corridor connecting Badami, Pattadakal and Aihole UNESCO World Heritage sites.")
                    .location("Badami, Bagalkot").pincode("587201").district("Bagalkot").state("Karnataka")
                    .budgetAllocated(1200000000.0).budgetSpent(360000000.0)
                    .status("IN_PROGRESS").completionPercentage(30)
                    .startDate("2024-01-01").expectedCompletionDate("2026-12-31")
                    .sanctioningAuthority("Ministry of Tourism / ASI / Karnataka Tourism Dept")
                    .contractor("KSTDC + ASI Empanelled Contractors").sourceLink("https://karnatakatourism.org/").build());

        if (!projectRepo.existsById("PRJ055"))
            projectRepo.save(Project.builder().id("PRJ055").name("Bengaluru-Mysuru Expressway Service Roads & Flyovers")
                    .category("ROAD").description("Service roads, underpasses and grade separators along the 117 km Bengaluru-Mysuru Expressway.")
                    .location("Ramanagara").pincode("562159").district("Ramanagara").state("Karnataka")
                    .budgetAllocated(4500000000.0).budgetSpent(2700000000.0)
                    .status("IN_PROGRESS").completionPercentage(60)
                    .startDate("2023-04-01").expectedCompletionDate("2025-09-30")
                    .sanctioningAuthority("NHAI / Ministry of Road Transport & Highways")
                    .contractor("Dilip Buildcon Ltd").sourceLink("https://nhai.gov.in/").build());

        if (!projectRepo.existsById("PRJ056"))
            projectRepo.save(Project.builder().id("PRJ056").name("Ramanagara Silk Reeling & Cocoon Market Modernisation")
                    .category("INDUSTRY").description("Modernisation of Ramanagara Central Silk Cocoon Market and 60 silk reeling units.")
                    .location("Ramanagara").pincode("562159").district("Ramanagara").state("Karnataka")
                    .budgetAllocated(850000000.0).budgetSpent(255000000.0)
                    .status("IN_PROGRESS").completionPercentage(30)
                    .startDate("2024-05-01").expectedCompletionDate("2026-04-30")
                    .sanctioningAuthority("Central Silk Board / Karnataka Sericulture Dept")
                    .contractor("Karnataka Silk Industries Corporation").sourceLink("https://www.ksic.in/").build());

        if (!projectRepo.existsById("PRJ057"))
            projectRepo.save(Project.builder().id("PRJ057").name("Kempegowda International Airport Phase 2 - Terminal 2")
                    .category("TRANSPORT").description("New Terminal 2 at Bengaluru KIA with 25 million passenger capacity annually.")
                    .location("Devanahalli, Chikkaballapur").pincode("562149").district("Chikkaballapur").state("Karnataka")
                    .budgetAllocated(130000000000.0).budgetSpent(110000000000.0)
                    .status("IN_PROGRESS").completionPercentage(85)
                    .startDate("2019-05-01").expectedCompletionDate("2025-06-30")
                    .sanctioningAuthority("AAI / BIAL / Ministry of Civil Aviation")
                    .contractor("L&T Construction / Simplex Infrastructures").sourceLink("https://bengaluruairport.com/").build());

        if (!projectRepo.existsById("PRJ058"))
            projectRepo.save(Project.builder().id("PRJ058").name("Chikkaballapur District Horticulture Cold Chain Network")
                    .category("AGRICULTURE").description("Network of 25 cold storage facilities for tomato, potato and flower growers in Chikkaballapur.")
                    .location("Chikkaballapur").pincode("562101").district("Chikkaballapur").state("Karnataka")
                    .budgetAllocated(1200000000.0).budgetSpent(480000000.0)
                    .status("IN_PROGRESS").completionPercentage(40)
                    .startDate("2024-01-01").expectedCompletionDate("2025-12-31")
                    .sanctioningAuthority("Ministry of Food Processing / Karnataka Horticulture Dept")
                    .contractor("National Horticulture Board + SFAC").sourceLink("https://nhb.gov.in/").build());

        if (!projectRepo.existsById("PRJ059"))
            projectRepo.save(Project.builder().id("PRJ059").name("Karwar Naval Base Expansion - INS Kadamba")
                    .category("INDUSTRY").description("Expansion of Project Seabird at INS Kadamba, Karwar — largest naval base in Asia.")
                    .location("Karwar, Uttara Kannada").pincode("581301").district("Uttara Kannada").state("Karnataka")
                    .budgetAllocated(190000000000.0).budgetSpent(110000000000.0)
                    .status("IN_PROGRESS").completionPercentage(58)
                    .startDate("2005-01-01").expectedCompletionDate("2027-12-31")
                    .sanctioningAuthority("Ministry of Defence / Indian Navy")
                    .contractor("L&T Defence + Hindustan Shipyard Ltd").sourceLink("https://indiannavy.nic.in/").build());

        if (!projectRepo.existsById("PRJ060"))
            projectRepo.save(Project.builder().id("PRJ060").name("Gokarna-Murdeshwar Coastal Tourism Circuit")
                    .category("TOURISM").description("Comprehensive tourism infrastructure along the Uttara Kannada coastline — roads, beach promenade, pilgrimage facilities.")
                    .location("Gokarna, Uttara Kannada").pincode("581326").district("Uttara Kannada").state("Karnataka")
                    .budgetAllocated(900000000.0).budgetSpent(270000000.0)
                    .status("IN_PROGRESS").completionPercentage(30)
                    .startDate("2024-06-01").expectedCompletionDate("2026-09-30")
                    .sanctioningAuthority("Karnataka Tourism Dept / PRASAD Scheme / Ministry of Tourism")
                    .contractor("KSTDC + Uttara Kannada Zilla Panchayat").sourceLink("https://karnatakatourism.org/").build());

        log.info("Projects seeded. Total in DB: {}", projectRepo.count());
    }
}